services:
  todo-service:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: todo_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - todo-service-data:/var/lib/postgresql/data
    ports:
      - "5467:5432"
    networks:
      - todo-list-network

  todo-service-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8060:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://todo-service:5432/todo_service_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - todo-service
    networks:
      - todo-list-network

volumes:
  todo-service-data:
networks:
  todo-list-network:
    external: true