spring:
  application:
    name: todo-service
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5443/todo_service_db
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
